export function allCountry() {
    const country = [
        "Albanie",
        "Allemagne",
        "Andorre",
        "Autriche",
        "Belgique",
        "Biélorussie",
        "Bosnie-Herzégovine",
        "Bulgarie",
        "Chypre",
        "Croatie",
        "Danemark",
        "Espagne",
        "Estonie",
        "Finlande",
        "France",
        "Grèce",
        "Hongrie",
        "Irlande",
        "Islande",
        "Italie",
        "Kosovo",
        "Lettonie",
        "Liechtenstein",
        "Lituanie",
        "Luxembourg",
        "Macédoine du Nord",
        "Malte",
        "Moldavie",
        "Monaco",
        "Monténégro",
        "Norvège",
        "Pays-Bas",
        "Pologne",
        "Portugal",
        "Roumanie",
        "Royaume-Uni",
        "Russie",
        "Saint-Marin",
        "Serbie",
        "Slovaquie",
        "Slovénie",
        "Suède",
        "Suisse",
        "Tchéquie",
        "Ukraine",
        "Vatican"
    ];

    return country;
}